org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true

mod.id=deeprealm_4th
mod.name=Deep Realm: The Forth
mod.version=0.1.8
mod.group=com.tonywww.deeprealm4th
mod.authors=Tony
mod.description=Explore the Fourth Layer: four biome ribbons spiraling into a central void.
mod.license=All Rights Reserved
