modLoader = "javafml"
loaderVersion = "${loaderRange}"
license = "${license}"

[[mixins]]
config = "deeprealm_4th.mixins.json"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''${description}'''

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoForgeRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "curios"
type = "required"
versionRange = "${curiosRange}"
ordering = "NONE"
side = "BOTH"
